server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
    session:
      timeout: 60m

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mariadb://localhost:3306/my_db
    driver-class-name: org.mariadb.jdbc.Driver
    username: user
    password: 123456


  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true


jwt: secret-value